### ISSUE TITLE
Typo in turn server credentials

### ISSUE THREAD

**Issue by shahidhafiz** [hnasr/javascript_playground#19]
PeerA.js replace urls with url and credentials with credential in the following code.
iceConfiguration.iceServers.push({
                url: 'turn:my-turn-server.mycompany.com:19403',
                username: 'optional-username',
                credential: 'auth-token'
            })

Also replace 
                urls: 'turn:stun1.l.google.com:19302' 
with 
                'url': 'stun:stun.l.google.com:19302'

**Comment by hnasr** [comment]
That is the syntax in MDN 

https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/urls
